### ISSUE TITLE
When I am trying to run the Mesh flow stabilization for real time video stabilization I am getting the below error

### ISSUE THREAD

**Issue by Shivarama123** [sudheerachary/Mesh-Flow-Video-Stabilization#11]

**Comment by sudheerachary** [comment]
python version == '2.7.12'
opencv version == '4.1.1'
numpy version == '1.16.4'
cvxpy version == '1.0.24'

It works on linux [not sure about windows]. Though the code runs on offline saved videos, the processing of frames, stabilization is done in real-time procedure. But, its not displayed in real-time.

**Comment by Shivarama123** [comment]
May I please know whether there is any possibility that it can be displayed real-time ?

**Comment by sudheerachary** [comment]
Yes, Its possible. If you understand the code flow its just a matter of re-arranging the pipeline module.

**Comment by Shivarama123** [comment]
That means whatever the updated real-time procedure here is capable of processing the videos real-time by taking the frames from webcam and store it in a file. ? 

May I please know whether this conclusion understood by me is correct?

And I think it's possible to show it real-time just by changing where you are writing it into a file using the video writer object right? (rather than concatenating old and stabilized frame, we can only display the new frame right?

please help me with this final one, it will help me a lot with my project
