### ISSUE TITLE
Please Help!

### ISSUE THREAD

**Issue by oloa** [sudheerachary/Mesh-Flow-Video-Stabilization#3]
@sudheerachary, Thanks for such an awesome work,

### I have a few questions as following and need your help with it:
- _How did you come up with this code? Did you approach the authors of the respected paper or you re-invented it from scratch yourself?_
- _This code isn't performance efficient, I managed to reduce the time by eliminating few nested loops and queuing frames but still cannot reach near the performance as mentioned in the referred paper since I'm unable to understand most of the code._ **Can you please explain the workflow of this code/Update repo. with explanatory comments in codes, so that I can be able to replace it with better libraries such as scipy and even with OpenCV's new algorithms which are more performance efficient?**

Thankyou

**Comment by sudheerachary** [comment]
@oloa, Thanks
- I had implemented the paper from scratch, with reference from the [code](https://github.com/AlbusPeter/MeshFlow_Video_Denoising) of similar [paper](http://www.liushuaicheng.org/ICIP/2017/index.html)
- Yes, I have to go through the code to explain. will update the repo soon with a doc explaining each module
comment if you have any further issues with code/docs

**Comment by oloa** [comment]
@sudheerachary there are many nested **for loops** in the code, this surely a big bottleneck for performance, these loops are added(replaced by original algorithms) in order to make code simple as stated in this original [source code](https://github.com/AlbusPeter/MeshFlow_Video_Denoising/blob/master/README.md). He stated in readme:

> This source code may not have the same processing speed as the paper illustrated. Because I replace the original matching algorithm into a simple one. This may also influence the quality of the denoising result a little

Hence we need those replaced algorithms back, Right now quality is surely good but performance is pretty bad.

**Comment by oloa** [comment]
Hey @sudheerachary , Check this out:
- ### Problem 1:
```
 def generate_vertex_profiles(x_paths, y_paths, x_motion_mesh, y_motion_mesh):
    """
    @param: x_paths is vertex profiles along x-direction
    @param: y_paths is vertex profiles along y_direction
    @param: x_motion_mesh is obtained motion mesh along 
            x-direction from motion_propogate()
    @param: y_motion_mesh is obtained motion mesh along 
            y-direction from motion_propogate()
    Returns:
            returns updated x_paths, y_paths with new 
            x_motion_mesh, y_motion_mesh added to the 
            last x_paths, y_paths
    """
    new_x_path = x_paths[:, :, -1] + x_motion_mesh
    new_y_path = y_paths[:, :, -1] + y_motion_mesh
    x_paths = np.concatenate((x_paths, np.expand_dims(new_x_path, axis=2)), axis=2)
    y_paths = np.concatenate((y_paths, np.expand_dims(new_y_path, axis=2)), axis=2)
    return x_paths, y_paths
```
So above you're expanding **axis=2** with new paths by concatenating the previous paths-array with current path-array.

_But that is instead making `path-arrays(i.e. x_path,y_path) size bigger as the number of frame/number of paths tends to increase`_, **How to avoid this? Is there any alternate approach to this method? Cannot we just process a limited number of frame and delete previous path-arrays data?**


- ### Problem 2:
In MeshFlow.py

```
    for i in range(x_motion_mesh.shape[0]-1):
        for j in range(x_motion_mesh.shape[1]-1):

            src = [[j*PIXELS, i*PIXELS],
                   [j*PIXELS, (i+1)*PIXELS],
                   [(j+1)*PIXELS, i*PIXELS],
                   [(j+1)*PIXELS, (i+1)*PIXELS]]
            src = np.asarray(src)
            
            dst = [[j*PIXELS+x_motion_mesh[i, j], i*PIXELS+y_motion_mesh[i, j]],
                   [j*PIXELS+x_motion_mesh[i+1, j], (i+1)*PIXELS+y_motion_mesh[i+1, j]],
                   [(j+1)*PIXELS+x_motion_mesh[i, j+1], i*PIXELS+y_motion_mesh[i, j+1]],
                   [(j+1)*PIXELS+x_motion_mesh[i+1, j+1], (i+1)*PIXELS+y_motion_mesh[i+1, j+1]]]
            dst = np.asarray(dst)
            H, _ = cv2.findHomography(src, dst, cv2.RANSAC)
            
            for k in range(PIXELS*i, PIXELS*(i+1)):
                for l in range(PIXELS*j, PIXELS*(j+1)):
                    x = H[0, 0]*l+H[0, 1]*k+H[0, 2]
                    y = H[1, 0]*l+H[1, 1]*k+H[1, 2]
                    w = H[2, 0]*l+H[2, 1]*k+H[2, 2]
                    if not w == 0:
                        x = x/(w*1.0); y = y/(w*1.0)
                    else:
                        x = l; y = k
                    map_x[k, l] = x
map_y[k, l] = y
```
**Can you explain the process and functioning of these lines? Is there alternate approach to this ?** (_as this is the most calculation expensive function in your code_)
