### ISSUE TITLE
an error or imperfection when the frame don't have any feature point

### ISSUE THREAD

**Issue by zhongtao93** [sudheerachary/Mesh-Flow-Video-Stabilization#4]
In mesh_flow.ipynb , an error occur when one frame has no feature point:
`# calculate optical flow`
` p1, st, err = cv2.calcOpticalFlowPyrLK(old_gray, frame_gray, p0, None, **lk_params)`

This problem occur definitely when a video has a blank or black frame, can you provide a more rebust code for this solution.

Thank you very much!

**Comment by zhongtao93** [comment]
I had fixed it, thx

**Comment by manaclan** [comment]
> I had fixed it, thx

how did you fix it? I'm having the same issue
